Vagrant.configure("2") do |config|

  config.vm.box = "nixos/nixos-18.03-x86_64"
  config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
  end

end
